name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --break-system-packages || pip install -r requirements.txt
      - name: Run lightweight tests
        run: |
          python run_tests.py
      - name: Run pytest (best-effort)
        continue-on-error: true
        run: |
          python -m pip install pytest --break-system-packages || python -m pip install pytest
          pytest -q || true
