name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Install core dependencies (excluding manim which requires system libs)
          pip install -r requirements-ci.txt --break-system-packages || pip install -r requirements-ci.txt
          # Try to install manim (optional - only needed for visualization)
          pip install manim==0.19.0 --break-system-packages || echo "Manim installation failed - this is OK for CI as it's only used for visualization"
      - name: Run lightweight tests
        run: |
          python run_tests.py
      - name: Run pytest (best-effort)
        continue-on-error: true
        run: |
          python -m pip install pytest --break-system-packages || python -m pip install pytest
          pytest -q || true
